### PR TITLE
add example-plugin and python script to create new blank project

### PR DESCRIPTION
**Pull request by abaga129**
I felt that it would be useful to have a simple way to create a new project.  The script can by run with "python newproject.py" from the examples folder.  It will ask for plugin name, vender name, etc.  I created a new example called "example-plugin" which is essentially a stripped down version of the distort example which is used to duplicate from.

### CODE REVIEW

**Comment by p0nce** [comment]
Hi,

I have some questions :
- why do you need to have `example-plugin`? The correct way for me would be to `git clone --depth=1 dplug.git` in a temporary directory and copy the distort example from there.

I know there is redundancy between plugin.json and `buildPluginInfo`. If this is the problem you are solving I could work on a way to avoid that.

Before spending time on a PR, _please_ discuss before in the bugtracker whether it would be accepted or not. In my experience this always lead to a better outcome.
There is no python in this repositery, and tools are all written in D so I'm not sure why you think this should be accepted.

To save you some time, I'll say before-hand that I won't accept python programs.

**Comment by abaga129** [comment]
My apologies for not discussing it in the bugtracker first.  This is my first time making a PR for a major repository like this so I hope I didn't waste too much of your time.  My intention was to have a blank project from which to duplicate from which would make it easier for new users to get started.

I used python just because it good at these kinds of tasks and I was influence by wdl which has a python script that does something similar.  I did consider using D since the whole repository is in D but figured python would be better for this sort of thing.

Once again I apologize!  This package is excellent and I am greatful for you making it open source.  If there is anything that I can do to contribute I would love to, but next time I will definitely use the bugtracker first.

**Comment by p0nce** [comment]
No problem at all don't apologize! It's me who is really sorry to have to turn down a contribution.
It's painful to have your contribution turn down whatever the reason, and it's my duty to me more accepting as you would be the very first outside contributor.

Dplug is not really major, it's not supposed to be hard to contribute.
I've added CONTRIBUTING.md to avoid further pain.

It's true that for now I was expecting users to copy/paste `distort/` and change values, if you can give the reasons why you didn't found it practical please do. Basically onboarding could be better.

There is the issue #105 which would lessen the work of making a new plugin, the information is currently duplicated. `plugin.json` is needed in part because of macOS packaging of plugins.
It is a challenging bug because plugins are `@nogc` but JSON parsers usually throw exceptions. It would be interesting to parse this information at compile-time!

```
abstract PluginInfo buildPluginInfo();
```

would be replaced in dplug/client/dplug/client.d by:
```
enum PluginInfo pluginInfo = parsePlugingInfo!("plugin.json");
```

**Comment by abaga129** [comment]
Thank you very much for taking the time to explain all of that. I read the CONTRIBUTING.md so now I understand the guidelines a little better.  I am definitely interested in issue #105.  I'm going to do a little reading into the source code and see if it is within my capabilities.

One quick question,  Is it not possible to simply parse the source file, for example "plugin.d" in the release tool since it already contains the plugin info?  Then there would be no need for plugin.json. Parsing the source file may be difficult but maybe using something like std.regex would help.

**Comment by p0nce** [comment]
You are right that there is two solutions for reducing redundancy, parsing plugin.json or parsing the right D  file.

My line of reasoning was :

**Advantages for plugin.json**
A1 - parsing JSON is way simpler than parsing D files.
A2 - more than that, it way requires a simple interpreter to be clean
A3 - the function `buildPluginInfo` should be runtime anyway, since the values are immutable
A4 - in the prospective future, some code could be disabled based on a compile-time value.
A5 - rule of Least Power https://en.wikipedia.org/wiki/Rule_of_least_power  
  Declarative may enable more things than a powerful language, hence why dub/npm uses JSON.
A6 - parsing D with regexp exposes me to mockery when it breaks :)

**Advantages for parsing D files and searching for the buildPluginInfo` function**
B1 - no need for JSON file
B2 - one single language
B3 - `buildPluginInfo` could be a template anyway

B3 and A3 cancel out themselves.

**Comment by p0nce** [comment]
Closing this PR in favor of #105

**Pull request closed without merging**
