### PR TITLE
add flat-widgets subpackage

### PR DESCRIPTION
**Pull request by abaga129**
This subpackage currently only contains

- UIFilmstripKnob (draws a knob from an filmstrip created with programs like knobman)
- UIFilmstripSlider (draws a slider from an filmstrip image)
- UIFlatSwitch (draws a switch from two images representing it's on and off states)

This adds the basic functionality necessary for pre-rendered UIs.  Some future additions that would be nice would be something similar to PBRBackgroundGUI but would take an image to draw as the background.  And a way to implement image based radio buttons would be nice also.

### CODE REVIEW

**Comment by abaga129** [comment]
I will replace the tabs as soon as possible. 
I wasnt aware of the visible concept being implemented. And infact that was something I was experimenting with and I shouldnt need any longer since children can be removed.
Feel free to remove the dead code.  Some of it is probably remnants from copying the pbr widgets.

**Comment by abaga129** [comment]
I cleaned everything up now
- replaced the tabs with spaces
- Removed code that wasn't be used
- Moved _height and _width to be protected fields.
- removed hide() and unhide()
The _disabled concept is something I implemented to make it easy for demo plugins.  When `disable()` is called, then `_disabled` is set to true which prevents any changes from mouse interaction.  This way the element is drawn but cant be changed except through presets or automation.

**Comment by p0nce** [comment]
Thanks. Let's include this disabled for now.

**Comment by p0nce** [comment]
This is v5.0.1

**Pull request merged**
