### PR TITLE
Better support for all alphanumeric keys and new Textbox widget (windows and x11)

### PR DESCRIPTION
**Pull request by abaga129**
Whats missing
- Special characters such as "!@#$%^&*()<>?"
- Implementation in Carbon and Cocoa

Adding the other keys will probably be trivial.  I just wanted to get the alphanumeric keys done atleast first.\

The Textbox widget is a work in progress, but should work well for most applications.

### CODE REVIEW

**Comment by p0nce** [comment]
This is a huge PR, I'll look at it over the following week if you don't mind.

**Comment by abaga129** [comment]
Thats fine. I'm not in any hurry to get this added. I started it a few months ago, and just now had time to finish it.  I'm aware that there is a lot to look over.
Thanks!

**Comment by p0nce** [comment]
Some questions:

A - Would it be possible to rebase and merge in one commit?

B - Would it be possible to manage keys in Windows more like in X11? It seems strange to me that we have to track SHIFT and transform 'a' into 'A' ourselves. My fear is that this will break with say eastern keyboard types. I'd much prefer we get a 'A' from the OS directly.

C - I think `CharStack` in textbox.d should go away in favor of a Vec!char. It doesn't seem you need it zero-terminated (and if you do, there are other ways to do it froma slice)

D - I think `getCharFromKey` should go near  `Key` definition instead of textbox.d. 
It should also return a `dchar`, even if that means mking textbox.d "incorrect" with a cast at first.

Let me know which items you wan't to do, those you disagree with, etc :)

**Comment by abaga129** [comment]
A - Yes I can do that, I understand that it is a lot of commits (some not necessary).
B - I thought about this after I made this PR.  I do believe it is possible to shrink the switch statement and do something like `case VK_a: .. case VK_z: return shiftpressed? some_logic_here`  However I dont think it is possible to avoid tracking the shift with windows virtual key codes.  If you know otherwise then I am definitely in favour of doing it a different way.
C - I'll look into using `Vec!char`.  I hadnt thought of that.  If it works then that would help shrink textbox.d a lot.

D - is `dchar` specific to dplug? I havent seen that anywhere, However I am in favour of moving `getCharFromKey` to window.d

E - Those pesky tabs always get me! I even searched for them this time before making a PR.  I'm not sure how they got passed me

Thanks for reviewing the pull request!  I know its big and maybe a little messy.  Hopefully we can get it up to standards!

**Comment by p0nce** [comment]
Re: B. I don't mind if we track VK_SHIFT for now, as it can be fixed later if this becomes a problem. Perhaps at some future point we'll need to have (key code + eventually codepoint) instead of just an enum for `Key`.

`dchar` is a standard D type for a 32-bit Unicode codepoint.

I'll merge when you fix C and D.

**Comment by abaga129** [comment]
Okay I will try to make those fixes very soon.

**Comment by p0nce** [comment]
Failing checks are because of another test. I'm merging and opening a new ticket for Cocoa/Carbon (assigned to me). Don't expect this done before one week though.

Note:

instead of 
```
const(char)[] displayString() nothrow @nogc
{
       stringBuf = charBuffer[0..charBuffer.length];
       return stringBuf[0..charBuffer.length];
}
```
you can also do:

```
const(char)[] displayString() nothrow @nogc
{
       return charBuffer[];
}
```

which calls `Vec!T.opSlice()`

**Pull request merged**
