### PR TITLE
make some optimizations to x11window

### PR DESCRIPTION
**Pull request by abaga129**
I've made the thread that checks for events and redraws the screen sleep for 16.6666 milliseconds at a time which translates to about 60 frames per second.  This has brought the CPU load down considerably and also simulates a timer for onAnimate.

There may be a better way to do this as suggested by @p0nce, but this does seem to work fairly well.  Only testing will say for sure.

Also I had to temporarily remove a few lines fron the Destructor which free memory used by the X display because they were causing a crash when closing the UI.  I think this may be due to the thread trying to acces the memory after its already been freed.

### CODE REVIEW

**Comment by p0nce** [comment]
This is v4.6.6

**Comment by p0nce** [comment]
Thanks a lot !

**Comment by abaga129** [comment]
Glad to help! Linux support is very important to my anyways.  I will continue working on it to see what improvements can be made.  I want to see about getting Ardour supported since it is probably the most widely used host on Linux.

**Comment by p0nce** [comment]
You can add additional entry points in dplug.vst.client prelude.

**Pull request merged**
