### PR TITLE
Resizable UIs

### PR DESCRIPTION
**Pull request by abaga129**
Most of the infrastructure was already in place to support resizable UIs.  The main hurdle was that static resources like background images couldn't be easily resized.  I've added a new function to resize a source `ImageRef` to a destination `ImageRef` using bilinear interpolation.

Existing plug-ins will need to override `void reflow(box2i availableSpace)` in their UIElements and also call `reflow` with the new positions when updating positions in order for the scaling to take place.  Currently this is a breaking change so it will either need to be in Dplug v10 or we will need to find a way to make this an optional feature.

This is still a work in progress but I wanted to go ahead and open it for review and feedback.

Checklist
- [x] Bilinear interpolation for ImageRefs]
- [x] Resizable MipMaps (needed for `UIImageKnob`)
- [x] Convert flat widgets
- [x] Convert PBR widgets
- [x] Canvas compatibility (throws an error in `linear_blit` currently when applying scaling)
- [x] Handle in LV2
- [x] Handle in VST
- [x] Handle in VST3
- [x] Handle in AU
- [x] Handle in Win32 window
- [x] Handle in X11 window
- [x] Handle in Cocoa window

### CODE REVIEW

**Comment by p0nce** [comment]
This is a big and very valuable change, so we might as well put that in v10, this will leave time for stabilization and complete implementation.

What we shouldn't do is require interfaces to support resizing. 

Ideally:

-  Maybe there should be a way to disable resizing, even if it changes some API. (possibly in `plugin.json`? or GUIGraphics constructor?). To avoid the case where the user resize the plugin window but it isn't supported by the GUI (widgets are not reflowed properly).

- Perhaps we should support plugins with incorrect `reflow()` somehow? If resizing is disabled. As the fix is rather simple, not sure if it's worth it. 

Ultimately, I think it should be possible to bring an existing plugin to Dplug v10 disabling resizing, and without reflowing correctly. The problem it avoids is not laziness, but in the case macOS Big Sur requires some breaking changes we could tackle it without forcing the Dplug user to implement correct widget resizing. It is practical?

**Comment by abaga129** [comment]
> without forcing the Dplug user to implement correct widget resizing. It is practical?

I think this is worth the effort.  There isnt many benefits for me to update some of my plug-ins with smaller UIs to this feature so it would be nice to continue using them as is but still be able to get v10 improvements.

**Comment by abaga129** [comment]
It seems that with VST + Windows when we request a resize, the window is infact resized but the WM_SIZE message is not sent to the window.  This could be related to #487. I'm beginning to think that when we request a resize from VST we need to somehow let the window know to call `_listener.onResize` on the next draw.

**Comment by p0nce** [comment]
It is possible that one request a resize to the host and it doesn't do anything.
If resize isn't detected by measurable window properties, maybe we shouldn't resize?

https://github.com/AuburnSounds/Dplug/blob/231e57e04762ce26f603ab7b0424d65ef2f2d1cd/window/dplug/window/win32window.d#L190

**Comment by abaga129** [comment]
I can verify that the issue with VST + resizing is that the resize event happens on the parent window so we dont get notified of it.  We just need to find out how to listen for this.

Changing this line https://github.com/AuburnSounds/Dplug/blob/231e57e04762ce26f603ab7b0424d65ef2f2d1cd/window/dplug/window/win32window.d#L175

To this will get the correct size. 
```D
BOOL res = GetClientRect(GetParent(_hwnd), &winsize);
```

**Comment by p0nce** [comment]
Reimplemented in #64

**Pull request closed without merging**
