### PR TITLE
X11 support

### PR DESCRIPTION
**Pull request by rikkimax**

### CODE REVIEW

**Comment by p0nce** [comment]
Hi @rikkimax . 
Thanks a lot for making this a reality.

**Comment by MartinNowak** [comment]
It no longer crashes, but the Window content isn't generated, I'm just seeing content of the previous background.
How did you test/develop that code @rikkimax?
I tried Renoise and am running w/ i3wm/Xorg.

**Comment by rikkimax** [comment]
Look under examples/window.

Good chance there is something not aligning up between my assumptions and
others code.

**Comment by p0nce** [comment]
@MartinNowak worked on Bitwig.
The idea is that it gets merged now (bugs included) and get fixed later by whoever is most interested in Linux.
Unlocking hosts for OSX and Windows took a lot of debugging over the course of 1.5 years each. So we can't expect @rikkimax to test every host variation on an itself diverse platform.

**Comment by p0nce** [comment]
Hi @MartinNowak , in master there should be no more TLS usage (TLS isn't allowed without runtime), maybe it fixes some crashes out there.
Does redrawing happen when you pass another window on top of the plugin one?

**Comment by abaga129** [comment]
Once I get around to it, I'll attempt to add support for Ardour since it is probably the most widely used Linux DAW

**Comment by p0nce** [comment]
Well the dream only started...

**Pull request merged**
