### PR TITLE
add FlatBackgroundGUI and fix UIFilmstripKnob not listening for param…

### PR DESCRIPTION
**Pull request by abaga129**
Changes
- I added a UIElement to simplify making a GUI for flat UIs.  I based it off of PBRBackgroundGUI. 
- A user noticed a bug with UIFilmstripKnob that it wasnt being redrawn when automated.  This was fixed by adding it as a param listener.

### CODE REVIEW

**Comment by p0nce** [comment]
- please call `_param.removeListener(this);`
- please add `public import dplug.flatwidgets.flatbackgroundgui;` in the corresponding `package.d`
- please indent using 4 spaces

**Comment by abaga129** [comment]
`_param.removeListener(this);` is already in the destructor.  And I added the import for `flatbackgroundgui` in flatwidgets/dplug/flatwidgets/package.d
I'll check the indentation

**Comment by abaga129** [comment]
Okay everything should be right now.  Those pesky tabs keep managing to get past me.

**Comment by p0nce** [comment]
v5.0.2

**Pull request merged**
