### PR TITLE
LV2 partial implementation

### PR DESCRIPTION
**Pull request by abaga129**
This is a large PR so I understand it will take some time to review.

A new test has been added `tests/lv2-plugin` which contains a bash script to build the distort example, and install it using `.ttl` files that are specific for the distort example.

The UI opens in JALV.GTK but not in Carla, however it is often distorted and very unresponsive.

**What's missing**

- MIDI Input
- getDAW() implementation (returns DAW.Unknown for now)
- dplug-build modification to generate `.ttl` files
- Windows support
- MacOS support

This is still very far from complete but it's a good first step I believe. :)

### CODE REVIEW

**Comment by p0nce** [comment]
Do you mind if review it early next week? I'll be quite busy until then. Thanks :)

**Comment by p0nce** [comment]
Hi Ethan!

I'll merge when the following points are adressed:

- [ ] merge conflicts, this needs rebasing from upstream (eg: https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)

- [ ] In copyright headers, please use a legal entity such as "Ethan Reker" rather than "Cut Through Recordings", else the copyright would not hold. This is an error I've corrected because "Copyright Auburn Sounds" makes no sense if "Auburn Sounds" is not an entity and cannot own things. No need to add "Copyright Guillaume Piolat"  if no snippet of mine is included in the file.

- [ ] Add your copyrigth under the original licence (not adding a new licence terms) in every `.d` file in `dplug:lv2`


**Optional**
- [ ] Please Remove "Author" part recently they tend to become outdated and are in the git history.
- [ ] strings that are `enum` could also be `static immutable` (super optional)

Let me know if you are willing to make those changes!

**Comment by abaga129** [comment]
Shouldnt be any problem to make those changes!  It may be a few days before I can get to it.  Thanks for reviewing it.

**Comment by abaga129** [comment]
Okay everything should be good to go now! I made the recommend changes and fixed the conflicts.

**Comment by p0nce** [comment]
Merged! Please comment in #307 what remains to be done!

**Comment by abaga129** [comment]
Thanks!

**Pull request merged**
